### ISSUE TITLE
file integrity check failed

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/related_resources#113]
file integrity check failed:

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by ntimo** [comment]
I also have this issue :( Please fix thanks

**Comment by jokay** [comment]
Duplicate of #106?

**Comment by kangaroo72** [comment]
Still existing with 1.0.2

**Comment by EmJotGeh** [comment]
For me 1.0.2 fix it

**Comment by kangaroo72** [comment]
Good idea
<img width="305" alt="grafik" src="https://user-images.githubusercontent.com/6906390/197763511-345d37b8-e029-4770-82b9-a779a8325401.png">
Thanks
