### ISSUE TITLE
Remove the test command

### ISSUE THREAD

**Issue by PVince81** [nextcloud/related_resources#19]
The test command was there before the UI existed, to check result validity.
Not sure if still useful.

We can either:
1) Remove it completely
or
2) Only show it when "debug" is true in config.php, so it can used for further development in the future when tweaking the algorithm ?

**Comment by PVince81** [comment]
@ArtificialOwl thoughts ?

**Comment by ArtificialOwl** [comment]
I think the test command should stay, it comes with details that you do not have on the ocs.
 I will however add a check on `'debug'`
