### ISSUE TITLE
Show groupfolder in related resources

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/related_resources#217]
if it is an exact match (i.e. talk room of a circle or else. Again, needs to be an exact match, so only show it if the groupfolder has assigned a single circle and nothing else and only show it it the other entity is also just linked to that single circle and nothing else)

**Comment by AndyScherzinger** [comment]
@ArtificialOwl you might want to look into this, maybe this is already a given, but I doubt it since groupfolders didn't support circles just yet.

**Comment by ArtificialOwl** [comment]
(wip) https://github.com/nextcloud/related_resources/pull/225

less simple that I previously though as it needs to be sligthly integrated to files also to manage resource related to current folder mapping when browsing a group folder.

**Comment by Pytal** [comment]
Tracking frontend in https://github.com/nextcloud/related_resources/issues/230
