### ISSUE TITLE
Add related resources panel to all places with "Add to a project"

### ISSUE THREAD

**Issue by Pytal** [nextcloud/related_resources#4]
- [x] https://github.com/nextcloud/nextcloud-vue/pull/3081
- [x] UI: completely hide the section in case of 0 results (only make it pop up once we got results) (done in https://github.com/nextcloud/nextcloud-vue/pull/3081)
- [ ] UI: in all places where "Add to a project", also add a panel of "related resources"
    - [x] files https://github.com/nextcloud/related_resources/pull/2 + https://github.com/nextcloud/related_resources/pull/33
    - [x] talk: under "shared items" tab https://github.com/nextcloud/spreed/pull/7789
    - [x] deck: under "board details" / sharing https://github.com/nextcloud/deck/pull/4000
    - [ ] calendar event: optional in sidebar somewhere ? https://github.com/nextcloud/calendar/pull/4498

<details>
<summary>Not needed</summary>

- deck: card detail popup (only Deck boards are linked against currently) https://github.com/nextcloud/related_resources/blob/cffb809b22c425aeeb6b88df2bd145722f94fe54/lib/RelatedResourceProviders/DeckRelatedResourceProvider.php#L133-L149

</details>

**Comment by Pytal** [comment]
![image](https://user-images.githubusercontent.com/24800714/186797869-fe48411a-6b58-4660-9991-614a113c86d7.png)

I see there is already a Resources tab in the event sidebar, what would be a good place for the related resources panel in the Calendar app @ChristophWurst @st3iny?

Example panel in the Talk sidebar
![image](https://user-images.githubusercontent.com/24800714/186301728-cf30677a-799a-4acd-8987-4ca5aa161ecb.png)

**Comment by jancborchardt** [comment]
@Pytal actually not really sure, it would fit more into "Details", especially since "Attachments" is there as well. But then the whole section is a bit much.

Maybe it’s better to move the current "Resources" to the event details, and move the "Attachments" as well as "Related resources" (both of which are Files / Media / etc) to a separate "Media" tab.

Then there would be 3 tabs still: Details, Attendees, Media.

**Comment by PVince81** [comment]
should be finishable now with the 7.1.0 final bump of nextcloud-vue

**Comment by AndyScherzinger** [comment]
open calendar aspect will be addressed via the projects work, so the item is considered completed
