### ISSUE TITLE
[Bug]: "Related Resources" in the sharing sidebar shows completely unrelated stuff

### ISSUE THREAD

**Issue by schiessle** [nextcloud/related_resources#59]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm not sure how Nextcloud decides what is a related resource or not.

But I have for example a customer project folder which shows as related resources pictures from our christmas party, internal documents like job descriptions, etc.

Which makes it even more worrying, this folder is shared with external contributors (guest users), do they see the same links? Probably yes, I don't assume that they are individually created for each person with access to the folder. I assume (and hope) that this persons can't open this documents because they where not shared with them. But filenames can already disclose information we don't want to share with external people.

Beside being completely useless with this random selection of files this looks like a potential privacy issue.

### Steps to reproduce

-

### Expected behavior

-

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by PVince81** [comment]
> they are individually created for each person with access to the folder.

yes they are, per user, limited by whatever you have access to, see https://github.com/nextcloud/related_resources/tree/master/lib/Service/RelatedService.php#L356

if you did find an example where someone actually saw files they should not have access to, please get in touch with @ArtificialOwl to have a look

**Comment by PVince81** [comment]
also I think in the guests app the related_resources app is not enabled by default

**Comment by ArtificialOwl** [comment]
I also tried with the related_resources app included in the guests allowed apps, same thing, cannot reproduce the described issue.
The share is generated the same way as direct share to a user; I see no reason for the mix of guest+related_resources to leak privacy data.

Now the fact that some data looks unrelated, it might be because some of the files are shares to everyone. This PR would filter low score result: #56

**Comment by schiessle** [comment]
Thanks for investigating! If the list is created for each user individually than it shouldn't be a privacy issue (my main concern). Having it by default disabled for guest creates a extra level of security, so this should be fine.

It still leaves me with completely useless and unrelated results for the files I checked, but that's a minor issue compared to what I feared at the beginning.
