### ISSUE TITLE
Use exact matching of share recipients

### ISSUE THREAD

**Issue by PVince81** [nextcloud/related_resources#84]
The base idea is to not use fuzzy logic based on scores but to use exact matching. This means that two resources are only considered related if they have the same exact set of share recipients on the highest entity level.

For example:
0) users U1, U2, U3 and U4 are members of a group G1
1) user U1 shares file F1 with group G1 and user U5 => sharee set is [G1, U5]
2) user U2 shares file F2 with group G1 and user U5 => sharee set is [G1, U5]
3) user U3 shares file F3 with group G1 => sharee set is [G1]
4) user U4 shares file F4 with user 5 => sharee set is [U5]

only in the cases where the sharee set is strictly the same, the resources are considered related.
So the related resources will be F1 and F2.
When user U1 or U2 open the share panel for F1 they will see F2 as related resource.
When user U1 or U2 open the share panel for F3 they will se no related resources.

**Comment by PVince81** [comment]
there are two conflicting scenarios where one or the other breaks depending whether we decide to include the share owner or not in the sharee set:

### Scenario 1:

1) U1 shares F1 to U2
2) U2 shares F2 to U1

if we don't include the share owner in the set, F1 and F2 are not related
for 1) the sharee set is [U2]
for 2) the sharee set is [U1]

if we do include the share owner, F1 and F2 will appear related:
for 1) the sharee set is then [U1, U2]
for 2) the sharee set is then [U2, U1]
=> the sets match, so the resources are related

## Scenario 2:

1) U1 shares F1 to G1
2) U2 shares F2 to G1
3) U3 created a room R2 and invites G1

if we don't include the share owner / creator in the set, F1 and F2 are related, but not connected to R2
for 1) F1 the sharee set is then [G1]
for 2) F2 the sharee set is then [G1]
for 3) R2 the sharee set is then [G1] (though, the creator is always a participant, so the set could be [U3, G1] anyway?)

if we do include the share owner / creator in the set, F1, F2 and R2 are NOT related:
for 1) F1 the sharee set is then [U1, G1]
for 2) F2 the sharee set is then [U2, G1]
for 3) R2 the sharee set is then [U3, G1]

we need to clarify what is the expected behavior in the two scenarios to resolve the conflict @ArtificialOwl

**Comment by ArtificialOwl** [comment]
As said during our conversation, the best practice would be to compare with a set of parameter including [share creator+share recipient] when comparing for a list of 1:1 shares, but not for 'group' shares.


U1, U2, U3, ... are users
G1, G2, G3, ... are groups
R1, R2, R3, ... are rooms
F1, F2, F3, ... are files


### scenario 1 - shares to users, no virtual group :-1:

U1 shares F1 to U2
U3 shares F2 to U2

- F1 and F2 are considered related.


### scenario 2 - shares between users using virtual group  :+1: 

U1 shares F1 to U2
U2 shares F1 to U3
U3 shares F2 to U1 and U2

Sets are a good way to link F1 and F2:
- F1 is shared to a virtual group ["U1", "U2", "U3"]
- F2 is shared to a virtual group ["U1", "U2", "U3"]
- We can assume that if a talk room exists with only U1, U2 and U3 then F1 and F2 will be displayed as related resource.
 
### scenario 3 - shares including groups not using virtual group  :+1: 

U1 shares F1 to G1, G2, C1
U2 shares F2 to G1, G2, C1

- F1 and F2 are related as shared to exact same group entities



### scenario 4 - shares including groups while using virtual group for users :-1: 

U1 shares F1 to G1
U2 shares F2 to G1

Using virtual group will unlink F1 (["U1", "F1", "G1"] and F2 ["U2", "F2", "G1"]


### Solution

**We cannot use the virtual group/set as soon as one of the shares recipient is a group entities**

- This will require some refactoring on the current state of the app.
- If we still want to takes into account shares to users and groups at the same time, but not share creator, there is some specific operation to be done; like in Talk, ignore the owner of the talk room if it is a user.


### scenario 3b - shares including groups and users:   :question: 

U1 shares F1 to G1, G2, C1
U2 shares F2 to G1, G2, C1

- F1 and F2 are related as shared to exact same group entities

U1 shares F1 to U3

- F1 and F2 are not related anymore, U3 being a member of G1, G2 or not at all.

**Comment by ArtificialOwl** [comment]
#88
